# Ops Agent Configuration file
logging:
  receivers:
    syslog:
      type: files
      include_paths:
        - /var/log/messages
        - /var/log/syslog
    spring:
      type: files
      include_paths: [/opt/spring/logs/*.log]
  service:
    pipelines:
      default_pipeline:
        receivers:
          - syslog
          - spring
metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
      collection_interval: 60s
  processors:
    metrics_filter:
      type: exclude_metrics
      metrics_pattern: []
  service:
    pipelines:
      default_pipeline:
        receivers: [hostmetrics]
        processors: [metrics_filter]

global:
  default_self_log_file_collection: false